### ISSUE TITLE
Links to pretrained and sequence are missing

### ISSUE THREAD

**Issue by stoneyang** [vcg-uvic/lf-net-release#1]
Hi, @kmyid ,

Thanks for sharing your excellent work! 

It seems than the links to the two important data as mentioned in the caption are dead. Could u please fix it? 

Thanks!

**Comment by kmyid** [comment]
We recently had an IT infra change. We are looking into it. I'll let you know ASAP

**Comment by kmyid** [comment]
Should be fine now.
