### ISSUE TITLE
Matching Score of SIFT on HPatches differs from SuperPoint

### ISSUE THREAD

**Issue by mfaisal59** [vcg-uvic/lf-net-release#10]
Hi,

The matching score of SIFT in table 6 of your paper is different from the one reported by SuperPoint authors in Table 4 of their paper, and is there anything that I am missing?

LFNet:
![image](https://user-images.githubusercontent.com/40632568/53320553-cf72de00-38f7-11e9-978d-5a94da840201.png)

SuperPoint:
![image](https://user-images.githubusercontent.com/40632568/53320573-dc8fcd00-38f7-11e9-9d57-98b2ec0d1f73.png)

**Comment by etrulls** [comment]
I see, the relevant numbers are .288 vs .313. That's not part of the standard hpatches benchmark (which is patch-based), so we ran it independently with different settings, even though we both used OpenCV.  We probably used different image sizes and keypoint numbers, and maybe even sampled the image pairs differently (I think we did first vs rest in every sequence; I'm not sure I'm reading the SP paper correctly but they might've done all possible pairs?).

We should've been more explicit here, but we ran this last-minute for the appendix. The point of this experiment was just to show how learned methods perform against hand-crafted methods w.r.t. the inlier threshold.
