### ISSUE TITLE
Can't download pretrained model again

### ISSUE THREAD

**Issue by hyzzsu** [vcg-uvic/lf-net-release#12]
hi ,  the pre-trained models can't be download right now.  ( It seem a relative issue before, but this problem happen again. )

http://webhome.cs.uvic.ca/~kyi/files/2018/lf-net/pretrained.tar.gz can't be reached.

**Comment by kmyid** [comment]
It's resolved again. We sometimes do have down times on the server for upgrades and I think you just tried at that time

**Comment by hyzzsu** [comment]
thanks a lot
