### ISSUE TITLE
Evaluate on HPatches benchmark

### ISSUE THREAD

**Issue by UCRajkumar** [vcg-uvic/lf-net-release#15]
Can you please provide a framework or some code snippet that will allow one to use your LF-net to benchmark on HPatches? For example, how to directly feed into the descriptor portion of LF-net? In particular, to recreate to some of the results presented in the paper?

**Comment by kmyid** [comment]
Hi,

Unfortunately, that part of the experiment would be hard to reproduce now that we are no longer at EPFL.
Sorry for the inconvenience.


> On Jul 21, 2019, at 04:54, URajkumar <notifications@github.com> wrote:
> 
> Can you please provide a framework or some code snippet that will allow one to use your LF-net to benchmark on HPatches? In particular, to recreate to some of the results presented in the paper?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Kwang Moo YI
Assistant Professor
Dept. of Computer Science,
University of Victoria
+1 (250) 472 5837
