### ISSUE TITLE
What are the thetas and inv_thetas of next batch?

### ISSUE THREAD

**Issue by ShrutheeshIR** [vcg-uvic/lf-net-release#22]
I understand that support is not provided for training, however, this is more an implementation query than a training query. 

In building the network, here 
https://github.com/vcg-uvic/lf-net-release/blob/12ba6ebf427cdcac1eebbbc36b3bdaf082809a02/train_lfnet.py#L246

What are the last 4 parameters, ```thetas1```, ```thetas2```, ```inv_thetas1``` and ```inv_thetas2```. According to the SfM data loader, as shown here:

https://github.com/vcg-uvic/lf-net-release/blob/12ba6ebf427cdcac1eebbbc36b3bdaf082809a02/mydatasets/sfmdataset.py#L590

They are not returning any values such as thetas1 etc. Quite simply, what are those, and where is the code snippet to get those?

Thanks

**Comment by kmyid** [comment]
It's been a while so I'm not entire sure, but I think this is some leftover from our previous attempts to also guide orientations? @xyukiono

**Comment by xyukiono** [comment]
Yes. rotation terms are used only for training to guide orientation estimates. thetas1 and thetas2 are in-plane rotation at camera movement from view1 to 2 and 2 to 1. inv-thetas1,2 are there inverse.

**Comment by ShrutheeshIR** [comment]
Alright! Thank you
