### ISSUE TITLE
raise ValueError('Miss finding argument: unparsed={}\n'.format(unparsed))

### ISSUE THREAD

**Issue by AmmarKamoona** [vcg-uvic/lf-net-release#23]
I am trying to extract features from png image but I got this error 

raise ValueError('Miss finding argument: unparsed={}\n'.format(unparsed))

However, I have tried to fix the error by adding the following line 
----------------------------------------------------------------------
if photo.ndim == 3 and photo.shape[-1] == 3:
            photo = np.array(photo, dtype=np.uint8)
            photo = cv2.cvtColor(photo, cv2.COLOR_RGB2GRAY)
----------------------------------------------------------
but this causes a new problem which I get always the same number of keypoint which is 500 for different images

**Comment by kmyid** [comment]
You simply need to pass in the number of keypoints that you want to extract at max

https://github.com/vcg-uvic/lf-net-release/blob/12ba6ebf427cdcac1eebbbc36b3bdaf082809a02/run_lfnet.py#L211
