### ISSUE TITLE
Links to Pre-Trained model and & Sequences are dead

### ISSUE THREAD

**Issue by mfaisal59** [vcg-uvic/lf-net-release#3]
Hi,
We are unable to download your pre-trained model and sequences.

**Comment by kmyid** [comment]
Hi, we are looking into it. seems like the hosting server has issues.

**Comment by mfaisal59** [comment]
Please update me, when issues are resolved.

**Comment by kmyid** [comment]
Seems like it was only a quick down time. Seems okay now

**Comment by mfaisal59** [comment]
Thanks, the issue is resolved.
