### ISSUE TITLE
where is the function 'euclidean_augmentation'  in train_lfnet from?

### ISSUE THREAD

**Issue by YvetteLaw** [vcg-uvic/lf-net-release#9]
In the line 702 of train_lfnet, there is a function named 'euclidean_augmentation' . Hoewever, I can't find the definition of it. 

Could you please tell me where is the definition of this function?

**Comment by xyukiono** [comment]
Hi, 
`euclidean_augmentation` is defined inside `mydatasets/__init__.py`.

**Comment by YvetteLaw** [comment]
I found it!
Thank you very much!
